# Generated by Django 4.1.5 on 2023-09-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_work_artist_artist_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='work',
        ),
    ]
