# Generated by Django 4.1.5 on 2023-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_artist_artist_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='work',
            field=models.ManyToManyField(related_name='artists', to='api.artist'),
        ),
    ]
