# Generated by Django 4.1.5 on 2023-09-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_artist_work_work_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work',
            new_name='artist',
        ),
    ]
